(cl:defpackage emotiv_epoc-srv
  (:use )
  (:export
   "CHANGEFREQUENCY"
   "<CHANGEFREQUENCY-REQUEST>"
   "CHANGEFREQUENCY-REQUEST"
   "<CHANGEFREQUENCY-RESPONSE>"
   "CHANGEFREQUENCY-RESPONSE"
  ))

