// Generated by gencpp from file emotiv_epoc/ChangeFrequencyRequest.msg
// DO NOT EDIT!


#ifndef EMOTIV_EPOC_MESSAGE_CHANGEFREQUENCYREQUEST_H
#define EMOTIV_EPOC_MESSAGE_CHANGEFREQUENCYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace emotiv_epoc
{
template <class ContainerAllocator>
struct ChangeFrequencyRequest_
{
  typedef ChangeFrequencyRequest_<ContainerAllocator> Type;

  ChangeFrequencyRequest_()
    : frequency(0)  {
    }
  ChangeFrequencyRequest_(const ContainerAllocator& _alloc)
    : frequency(0)  {
  (void)_alloc;
    }



   typedef uint32_t _frequency_type;
  _frequency_type frequency;




  typedef boost::shared_ptr< ::emotiv_epoc::ChangeFrequencyRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::emotiv_epoc::ChangeFrequencyRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ChangeFrequencyRequest_

typedef ::emotiv_epoc::ChangeFrequencyRequest_<std::allocator<void> > ChangeFrequencyRequest;

typedef boost::shared_ptr< ::emotiv_epoc::ChangeFrequencyRequest > ChangeFrequencyRequestPtr;
typedef boost::shared_ptr< ::emotiv_epoc::ChangeFrequencyRequest const> ChangeFrequencyRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::emotiv_epoc::ChangeFrequencyRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::emotiv_epoc::ChangeFrequencyRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace emotiv_epoc

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'emotiv_epoc': ['/home/robot/Centauri/Software/src/emotiv-ros/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::emotiv_epoc::ChangeFrequencyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::emotiv_epoc::ChangeFrequencyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::emotiv_epoc::ChangeFrequencyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::emotiv_epoc::ChangeFrequencyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::emotiv_epoc::ChangeFrequencyRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::emotiv_epoc::ChangeFrequencyRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::emotiv_epoc::ChangeFrequencyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "73ffa65309f649b8b694f03ce8799567";
  }

  static const char* value(const ::emotiv_epoc::ChangeFrequencyRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x73ffa65309f649b8ULL;
  static const uint64_t static_value2 = 0xb694f03ce8799567ULL;
};

template<class ContainerAllocator>
struct DataType< ::emotiv_epoc::ChangeFrequencyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "emotiv_epoc/ChangeFrequencyRequest";
  }

  static const char* value(const ::emotiv_epoc::ChangeFrequencyRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::emotiv_epoc::ChangeFrequencyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 frequency\n\
";
  }

  static const char* value(const ::emotiv_epoc::ChangeFrequencyRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::emotiv_epoc::ChangeFrequencyRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frequency);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChangeFrequencyRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::emotiv_epoc::ChangeFrequencyRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::emotiv_epoc::ChangeFrequencyRequest_<ContainerAllocator>& v)
  {
    s << indent << "frequency: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.frequency);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EMOTIV_EPOC_MESSAGE_CHANGEFREQUENCYREQUEST_H
