// Generated by gencpp from file emotiv_epoc/ChangeFrequencyResponse.msg
// DO NOT EDIT!


#ifndef EMOTIV_EPOC_MESSAGE_CHANGEFREQUENCYRESPONSE_H
#define EMOTIV_EPOC_MESSAGE_CHANGEFREQUENCYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace emotiv_epoc
{
template <class ContainerAllocator>
struct ChangeFrequencyResponse_
{
  typedef ChangeFrequencyResponse_<ContainerAllocator> Type;

  ChangeFrequencyResponse_()
    {
    }
  ChangeFrequencyResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::emotiv_epoc::ChangeFrequencyResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::emotiv_epoc::ChangeFrequencyResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ChangeFrequencyResponse_

typedef ::emotiv_epoc::ChangeFrequencyResponse_<std::allocator<void> > ChangeFrequencyResponse;

typedef boost::shared_ptr< ::emotiv_epoc::ChangeFrequencyResponse > ChangeFrequencyResponsePtr;
typedef boost::shared_ptr< ::emotiv_epoc::ChangeFrequencyResponse const> ChangeFrequencyResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::emotiv_epoc::ChangeFrequencyResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::emotiv_epoc::ChangeFrequencyResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace emotiv_epoc

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'emotiv_epoc': ['/home/robot/Centauri/Software/src/emotiv-ros/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::emotiv_epoc::ChangeFrequencyResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::emotiv_epoc::ChangeFrequencyResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::emotiv_epoc::ChangeFrequencyResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::emotiv_epoc::ChangeFrequencyResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::emotiv_epoc::ChangeFrequencyResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::emotiv_epoc::ChangeFrequencyResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::emotiv_epoc::ChangeFrequencyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::emotiv_epoc::ChangeFrequencyResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::emotiv_epoc::ChangeFrequencyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "emotiv_epoc/ChangeFrequencyResponse";
  }

  static const char* value(const ::emotiv_epoc::ChangeFrequencyResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::emotiv_epoc::ChangeFrequencyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::emotiv_epoc::ChangeFrequencyResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::emotiv_epoc::ChangeFrequencyResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChangeFrequencyResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::emotiv_epoc::ChangeFrequencyResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::emotiv_epoc::ChangeFrequencyResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // EMOTIV_EPOC_MESSAGE_CHANGEFREQUENCYRESPONSE_H
