// Generated by gencpp from file emotiv_epoc/ChangeFrequency.msg
// DO NOT EDIT!


#ifndef EMOTIV_EPOC_MESSAGE_CHANGEFREQUENCY_H
#define EMOTIV_EPOC_MESSAGE_CHANGEFREQUENCY_H

#include <ros/service_traits.h>


#include <emotiv_epoc/ChangeFrequencyRequest.h>
#include <emotiv_epoc/ChangeFrequencyResponse.h>


namespace emotiv_epoc
{

struct ChangeFrequency
{

typedef ChangeFrequencyRequest Request;
typedef ChangeFrequencyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ChangeFrequency
} // namespace emotiv_epoc


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::emotiv_epoc::ChangeFrequency > {
  static const char* value()
  {
    return "73ffa65309f649b8b694f03ce8799567";
  }

  static const char* value(const ::emotiv_epoc::ChangeFrequency&) { return value(); }
};

template<>
struct DataType< ::emotiv_epoc::ChangeFrequency > {
  static const char* value()
  {
    return "emotiv_epoc/ChangeFrequency";
  }

  static const char* value(const ::emotiv_epoc::ChangeFrequency&) { return value(); }
};


// service_traits::MD5Sum< ::emotiv_epoc::ChangeFrequencyRequest> should match 
// service_traits::MD5Sum< ::emotiv_epoc::ChangeFrequency > 
template<>
struct MD5Sum< ::emotiv_epoc::ChangeFrequencyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::emotiv_epoc::ChangeFrequency >::value();
  }
  static const char* value(const ::emotiv_epoc::ChangeFrequencyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::emotiv_epoc::ChangeFrequencyRequest> should match 
// service_traits::DataType< ::emotiv_epoc::ChangeFrequency > 
template<>
struct DataType< ::emotiv_epoc::ChangeFrequencyRequest>
{
  static const char* value()
  {
    return DataType< ::emotiv_epoc::ChangeFrequency >::value();
  }
  static const char* value(const ::emotiv_epoc::ChangeFrequencyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::emotiv_epoc::ChangeFrequencyResponse> should match 
// service_traits::MD5Sum< ::emotiv_epoc::ChangeFrequency > 
template<>
struct MD5Sum< ::emotiv_epoc::ChangeFrequencyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::emotiv_epoc::ChangeFrequency >::value();
  }
  static const char* value(const ::emotiv_epoc::ChangeFrequencyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::emotiv_epoc::ChangeFrequencyResponse> should match 
// service_traits::DataType< ::emotiv_epoc::ChangeFrequency > 
template<>
struct DataType< ::emotiv_epoc::ChangeFrequencyResponse>
{
  static const char* value()
  {
    return DataType< ::emotiv_epoc::ChangeFrequency >::value();
  }
  static const char* value(const ::emotiv_epoc::ChangeFrequencyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EMOTIV_EPOC_MESSAGE_CHANGEFREQUENCY_H
