// Generated by gencpp from file emotiv_epoc/EEGFrame.msg
// DO NOT EDIT!


#ifndef EMOTIV_EPOC_MESSAGE_EEGFRAME_H
#define EMOTIV_EPOC_MESSAGE_EEGFRAME_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace emotiv_epoc
{
template <class ContainerAllocator>
struct EEGFrame_
{
  typedef EEGFrame_<ContainerAllocator> Type;

  EEGFrame_()
    : header()
    , accel_x(0)
    , accel_y(0)
    , channel_count(0)
    , channel_names()
    , signals()
    , qualities()  {
    }
  EEGFrame_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , accel_x(0)
    , accel_y(0)
    , channel_count(0)
    , channel_names(_alloc)
    , signals(_alloc)
    , qualities(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _accel_x_type;
  _accel_x_type accel_x;

   typedef uint32_t _accel_y_type;
  _accel_y_type accel_y;

   typedef uint32_t _channel_count_type;
  _channel_count_type channel_count;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _channel_names_type;
  _channel_names_type channel_names;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _signals_type;
  _signals_type signals;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _qualities_type;
  _qualities_type qualities;




  typedef boost::shared_ptr< ::emotiv_epoc::EEGFrame_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::emotiv_epoc::EEGFrame_<ContainerAllocator> const> ConstPtr;

}; // struct EEGFrame_

typedef ::emotiv_epoc::EEGFrame_<std::allocator<void> > EEGFrame;

typedef boost::shared_ptr< ::emotiv_epoc::EEGFrame > EEGFramePtr;
typedef boost::shared_ptr< ::emotiv_epoc::EEGFrame const> EEGFrameConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::emotiv_epoc::EEGFrame_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::emotiv_epoc::EEGFrame_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace emotiv_epoc

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'emotiv_epoc': ['/home/robot/Centauri/Software/src/emotiv-ros/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::emotiv_epoc::EEGFrame_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::emotiv_epoc::EEGFrame_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::emotiv_epoc::EEGFrame_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::emotiv_epoc::EEGFrame_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::emotiv_epoc::EEGFrame_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::emotiv_epoc::EEGFrame_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::emotiv_epoc::EEGFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "86134851c3839c35d0c7eb7049a290b2";
  }

  static const char* value(const ::emotiv_epoc::EEGFrame_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x86134851c3839c35ULL;
  static const uint64_t static_value2 = 0xd0c7eb7049a290b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::emotiv_epoc::EEGFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "emotiv_epoc/EEGFrame";
  }

  static const char* value(const ::emotiv_epoc::EEGFrame_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::emotiv_epoc::EEGFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint32 accel_x\n\
uint32 accel_y\n\
\n\
uint32 channel_count\n\
string[] channel_names\n\
uint32[] signals\n\
uint32[] qualities\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::emotiv_epoc::EEGFrame_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::emotiv_epoc::EEGFrame_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.accel_x);
      stream.next(m.accel_y);
      stream.next(m.channel_count);
      stream.next(m.channel_names);
      stream.next(m.signals);
      stream.next(m.qualities);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EEGFrame_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::emotiv_epoc::EEGFrame_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::emotiv_epoc::EEGFrame_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "accel_x: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.accel_x);
    s << indent << "accel_y: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.accel_y);
    s << indent << "channel_count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.channel_count);
    s << indent << "channel_names[]" << std::endl;
    for (size_t i = 0; i < v.channel_names.size(); ++i)
    {
      s << indent << "  channel_names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.channel_names[i]);
    }
    s << indent << "signals[]" << std::endl;
    for (size_t i = 0; i < v.signals.size(); ++i)
    {
      s << indent << "  signals[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.signals[i]);
    }
    s << indent << "qualities[]" << std::endl;
    for (size_t i = 0; i < v.qualities.size(); ++i)
    {
      s << indent << "  qualities[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.qualities[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // EMOTIV_EPOC_MESSAGE_EEGFRAME_H
